### ISSUE TITLE
Issue preprocessing data to reproduce your experiments

### ISSUE THREAD

**Issue by mlpacheco** [kuribayashi4/span_based_argumentation_parser#2]
Hello, 

I am trying to reproduce these experiments, I am particularly interested in the PEC task. However, I run into a problem because the backpointers to the data files seem to be broken.

```
(span_based_argumentation_parser) fortytwo 58 $ bash preprocess.sh 0
preprocess.sh: line 1: data/acl2017-neural_end2end_am/data/conll/Essay_Level/all.dat: No such file or directory
preprocess.sh: line 2: data/acl2017-neural_end2end_am/data/conll/Paragraph_Level/all.dat: No such file or directory
Load persuasive essay corpus (PE)
Traceback (most recent call last):
  File "src/preprocess/load_text_essays.py", line 404, in <module>
    main(args.tag)
  File "src/preprocess/load_text_essays.py", line 15, in main
    with open("./data/acl2017-neural_end2end_am/data/conll/Paragraph_Level/all.dat") as f:
FileNotFoundError: [Errno 2] No such file or directory: './data/acl2017-neural_end2end_am/data/conll/Paragraph_Level/all.dat'
```

In fact, there doesn't seem to be an all.dat file in such directory when I manually check. Could you please make sure this is runnable? Or could I have access to the preprocessed data?

**Comment by mlpacheco** [comment]
Nevermind, I was able to figure this out. Sorry for the confusion.
